version: '3'

services:
  backend:
    build: 
      context: ./Backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  
  frontend:
    build: 
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: